### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by matteodefelice** [4castRenewables/climetlab-plugin-a6#12]
The examples don't work. 
Firstly, I have tried to install the plugin with `pip install climetlab-plugin-a6` but 
```
ERROR: Could not find a version that satisfies the requirement climetlab-plugin-a6
ERROR: No matching distribution found for climetlab-plugin-a6
```
The same trying with other way to spell the name, including the `climetlab_climetlab_plugin_a6` in the README.

Finally, I managed to install with `pip install climetlab-maelstrom-power-production`. The package downgraded my climetlab to 0.5.6 but at least it seems running.

**Comment by markusabel** [comment]
Hi Matteo, thanks for feedback. We will check what happens here.

**Comment by faemmi** [comment]
Thanks for your feedback. It seems the documentation is not up-to-date and that there has been a new release of CliMetLab, and our package is pinned to an older version.
